language: csharp
sudo: false

# Need 2.*, should keep up to date with security releases
dotnet: 2.0.3

matrix:
  include:

    - os: linux
      mono: 5.4.1

    - os: osx
      mono: 5.4.1

      # .NET Core 2 requires OSX 10.12+
      # https://github.com/dotnet/core/blob/master/release-notes/2.0/2.0-supported-os.md#macos
      # https://docs.travis-ci.com/user/reference/osx/#OS-X-Version
      osx_image: xcode9.1

script:
  - ./build.sh --target=Travis --configuration=Release
